services:
  - type: web
    name: crypto-arb-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && ls -R dist
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
